server:
  port: 8080
  # 指定项目名
  #servlet:
  #context-path: /test
  tomcat:
    max-connections: 10000
    max-threads: 10000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?useSSL=true&charset=utf8mb4&serverTimezone=Hongkong
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      database: '1'
      host: 127.0.0.1
      port: 6379
      password:
    jedis:
      pool:
        max-active: 10000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10000 # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
    timeout: 10000 # 连接超时时间（毫秒）
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.tg.blog.mo8080del
token:
  expire:
    seconds: 2592000 # 30*24*60*60*1000 = 2,592,000